### ISSUE TITLE
couldn't make it run with default vars

### ISSUE THREAD

**Issue by Dentrax** [fouadsemaan/ansible-dex#1]
Hey @fouadsemaan, any ideas on this?

```
TASK [andrewrothstein.unarchive-deps : resolve platform specific vars] *********
fatal: [default]: FAILED! => {"msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}
```

My playbook is simple:
```
- name: Dex
  hosts: default
  gather_facts: false
  become: true
  roles:
    - role: fouadsemaan.ansible_dex
```
